---
abstract: 'Loudly complain in lots of places when things break badly'
author:
  - 'Brian Conry <perl@theconrys.com>'
  - 'Jim Thomason <thomasoniii@yahoo.com>'
build_requires:
  Test::More: 0
  vars: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Carp-Notify
requires:
  perl: 5.005
  strict: 0
resources:
  repository: git://github.com/buc0/carp-notify.git
version: 1.11
